### PR TITLE
Update frontend

### PR DESCRIPTION
**Pull request by KTibow**
- Fix gitignore/dependencies/some formatting
- Split connection out into separate component (this does result in a bit of code duplication with the dev server but i think its better)
- Update UI flow

### CODE REVIEW

**Comment by CoolElectronics** [comment]
image
the wording here is pretty confusing, without any explanation of what the difference is people aren't going to know what that means

the ui stuff looks good, my only concern is that everything is kinda off-centered now that you made the connection thingy a dialogue box, now there's a bunch of extra space for no reason

i'm fine with merging as long as those two things are at least partially addressed, also it would be preferred if you made a commit for each change instead of doing everything at once (makes it easier to bisect)

**Comment by KTibow** [comment]
> the wording here is pretty confusing, without any explanation of what the difference is people aren't going to know what that means

what would you recommend instead? imo it's more clear than the previous version

> now there's a bunch of extra space for no reason

screenshot?

> also it would be preferred if you made a commit for each change instead of doing everything at once

not easy to do now

**Comment by CoolElectronics** [comment]
> what would you recommend instead? imo it's more clear than the previous version
well i mean unless you've read through the readme and are familiar with the project, "connect to your node" and "connect" have the exact same meaning semantically (even i was confused for a few seconds)

and at least the previous version had this text
image
which you seem to have removed and should probably be added back to the login screen

i would recommend something that's a little more descriptive to people who haven't read through the README, like "connect to personal node" "connect with login" "connect to home node" etc



as for the extra space,  i mean this
image
compared to this
image


i do appreciate the visual improvements of the connect dialogue but it just leaves a massive gaping hole where the old connection screen would be, so i would prefer you just revert back to the inline connection box unless you want to redesign the landing page to not have the gap where the box used to be

**Comment by KTibow** [comment]
> i would recommend something that's a little more descriptive to people who haven't read through the README, like "connect to personal node" "connect with login" "connect to home node" etc

third one sounds good

> i do appreciate the visual improvements of the connect dialogue but it just leaves a massive gaping hole where the old connection screen would be, so i would prefer you just revert back to the inline connection box unless you want to redesign the landing page to not have the gap where the box used to be

i'll have to mull over some possible designs - what do you think about having a centered connection box with the other content surrounding it?

**Comment by CoolElectronics** [comment]
if you think that you can make it more aesthetically pleasing and more original than what's on master go for it

**Comment by KTibow** [comment]
new page
image

**Comment by CoolElectronics** [comment]
yeah i think we should just keep some of the smaller improvements and revert back to the inline layout on master

**Comment by KTibow** [comment]
i'm not really sure what to say, given that i spent so long working on this, and i don't know how to compromise with the changes
if you want to make a list of your opinions on each change i could say my reaction? idk

**Comment by ProgrammerIn-wonderland** [comment]
> new page image

 Damn I'm rlly a fan of this new page

**Comment by ProgrammerIn-wonderland** [comment]
though I think some of the verbage should be changed, swarm mode def shouldn't be the default/highlighted option and it should be discouraged to some extent

**Comment by CoolElectronics** [comment]
gonna make some small changes to it real quick to see where it's at

**Comment by CoolElectronics** [comment]
i didn't realize the popup was always enabled, lol so it looked off to me this should work

**Comment by CoolElectronics** [comment]
image

i was thinking more keep the old top bar, something like this

but then the "tagline"/description sorta looks out of place, but there isn't anywhere else to put it.. thoughts?

**Comment by KTibow** [comment]
I would tweak the vertical alignment and move the icon to the left but aside from that it looks good to me

**Comment by CoolElectronics** [comment]
alright, it won't let me add commits to this pr directly so i'm just gonna close this and push to master

**Pull request merged**
